# Generated by Django 4.2.3 on 2024-01-12 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Autoriza'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.cargotrabajador', verbose_name='Cargo del trabajador'),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='salas',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='salas',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.puesto', verbose_name='puesto'),
        ),
        migrations.AddField(
            model_name='salas',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.unidad', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='parqueo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='parqueo',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.puesto', verbose_name='puesto'),
        ),
        migrations.AddField(
            model_name='parqueo',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.unidad', verbose_name='unidad'),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='n_parqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.parqueo', verbose_name='Numero de parqueo'),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvisitas',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvisitas',
            name='n_parqueo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.parqueo', verbose_name='Numero de Parqueo'),
        ),
        migrations.AddField(
            model_name='historicalvisitas',
            name='p_visita',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.trabajadores', verbose_name='Persona a quien visita'),
        ),
        migrations.AddField(
            model_name='historicalvisitas',
            name='sala',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.salas'),
        ),
        migrations.AddField(
            model_name='historicalvisitas',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Autoriza'),
        ),
        migrations.AddField(
            model_name='historicaltrabajadores',
            name='cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.cargotrabajador', verbose_name='Cargo del trabajador'),
        ),
        migrations.AddField(
            model_name='historicaltrabajadores',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicaltrabajadores',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalingresosalida',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalingresosalida',
            name='n_parqueo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.parqueo', verbose_name='Numero de parqueo'),
        ),
        migrations.AddField(
            model_name='historicalingresosalida',
            name='trabajador',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='historicalingresosalida',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equiposproteccionvisitante',
            name='visitante',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.visitas', verbose_name='Visitante'),
        ),
        migrations.AddField(
            model_name='asistentes',
            name='n_parqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.parqueo', verbose_name='Parqueo'),
        ),
        migrations.AddField(
            model_name='asistentes',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.visitas', verbose_name='Visita'),
        ),
        migrations.AddField(
            model_name='asignacionev',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='asignacionepps',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.trabajadores', verbose_name='Trabajador'),
        ),
    ]
