# Generated by Django 4.2.3 on 2024-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentes',
            name='sctr',
            field=models.FileField(blank=True, null=True, upload_to='strc/', verbose_name='SCTR'),
        ),
    ]
