# Generated by Django 5.0.4 on 2024-05-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_asistentes_sctr'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisitas',
            name='documento_empresa',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº RUC/DNI/CE/PP'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='documento_empresa',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº RUC/DNI/CE/PP'),
        ),
    ]
