# Generated by Django 4.2.3 on 2024-08-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_historicalvisitas_documento_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrabajadores',
            name='codigo_rfid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RFID'),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='codigo_rfid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RFID'),
        ),
        migrations.CreateModel(
            name='ControlCelepsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hora_ingreso', models.TimeField(auto_now_add=True, verbose_name='Hora de ingreso')),
                ('hora_salida', models.TimeField(verbose_name='Hora de salida')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.trabajadores', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Control de entrada y salida',
                'verbose_name_plural': 'Control de entrada y salida',
                'db_table': 'control_celepsa',
            },
        ),
    ]
