# Generated by Django 4.2.3 on 2024-08-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_historicaltrabajadores_codigo_rfid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcelepsa',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
    ]
