# Generated by Django 4.2.3 on 2024-08-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_controlcelepsa_hora_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltrabajadores',
            name='codigo_rfid',
        ),
        migrations.RemoveField(
            model_name='trabajadores',
            name='codigo_rfid',
        ),
    ]
