# Generated by Django 4.2.3 on 2024-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_remove_historicaltrabajadores_codigo_rfid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalingresosalida',
            old_name='fecha',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='ingresosalida',
            old_name='fecha',
            new_name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='historicalingresosalida',
            name='fecha_salida',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='ingresosalida',
            name='fecha_salida',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
    ]
