# Generated by Django 4.2.3 on 2024-08-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_historicalingresosalida_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalingresosalida',
            name='fecha_ingreso',
            field=models.DateField(auto_created=True, blank=True, editable=False, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='historicalingresosalida',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='historicalingresosalida',
            name='hora_ingreso',
            field=models.TimeField(auto_created=True, blank=True, editable=False, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='fecha_ingreso',
            field=models.DateField(auto_created=True, auto_now=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='ingresosalida',
            name='hora_ingreso',
            field=models.TimeField(auto_created=True, auto_now=True, null=True, verbose_name='Hora de salida'),
        ),
    ]
