# Generated by Django 5.1 on 2024-08-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_historicalingresosalida_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisitas',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
    ]
