# Generated by Django 5.1 on 2024-09-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_historicalvisitas_fecha_salida_visitas_fecha_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, unique=True, verbose_name='Area de trabajo')),
            ],
            options={
                'verbose_name': 'Area de trabajo',
                'verbose_name_plural': 'Areas de trabajo',
                'db_table': 'areas_trabajo',
            },
        ),
        migrations.DeleteModel(
            name='UnidadTrabajo',
        ),
        migrations.AddField(
            model_name='cargotrabajador',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.areatrabajo', verbose_name='Area de trabajo'),
        ),
    ]
