# Generated by Django 5.1 on 2024-09-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_areatrabajo_delete_unidadtrabajo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltrabajadores',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='historicaltrabajadores',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='historicaltrabajadores',
            name='history_user',
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.areatrabajo', verbose_name='Area de trabajo'),
        ),
        migrations.AddConstraint(
            model_name='cargotrabajador',
            constraint=models.UniqueConstraint(fields=('cargo', 'area'), name='unique_cargo_area'),
        ),
        migrations.DeleteModel(
            name='HistoricalTrabajadores',
        ),
    ]
