# Generated by Django 5.1 on 2024-09-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_historicaltrabajadores_area_trabajadores_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTrabajadores',
        ),
    ]
