# Generated by Django 5.1 on 2024-09-10 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_historicaltrabajadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.areatrabajo', verbose_name='Area de trabajo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.cargotrabajador', verbose_name='Cargo del trabajador'),
            preserve_default=False,
        ),
    ]
