# Generated by Django 4.2.3 on 2024-05-29 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_historicaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.empresa', verbose_name='Empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empresa asignada',
                'verbose_name_plural': 'Empresas asignadas',
                'db_table': 'user_empresas',
            },
        ),
    ]
