# Generated by Django 5.0.4 on 2024-06-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userempresas'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userempresas',
            constraint=models.UniqueConstraint(fields=('usuario', 'empresa'), name='unique_usuario_empresa'),
        ),
    ]
