# Generated by Django 5.0.4 on 2024-06-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userempresas_unique_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviacion'),
        ),
    ]
