# Generated by Django 5.0.6 on 2024-07-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_empresa_abreviacion'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
