# Generated by Django 5.0.6 on 2024-07-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenBearer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
