# Generated by Django 5.1 on 2024-08-29 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_tokenbearer_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_user',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Supervisor'), ('3', 'Usuario')], default='3', max_length=5, verbose_name='Tipo de usuario'),
        ),
        migrations.CreateModel(
            name='UserSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervised_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervised_by', to=settings.AUTH_USER_MODEL, verbose_name='Supervisado')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervised_users', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Usuarios a cargo',
                'db_table': 'users_supervisor',
                'constraints': [models.UniqueConstraint(fields=('supervisor', 'supervised_user'), name='unique_supervisor_supervised_user')],
            },
        ),
    ]
